[package]
name = "capyscheme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsgc = { path = "submodules/rsgc", default-features = false}                                        # { git = "https://github.com/playxe/rsgc" }
memoffset = "0.8"
env_logger = "0.10"
log = "0.4"
libc = "0.2"
r7rs-parser = {path = "r7rs-parser"} #{ git = "https://github.com/playxe/r7rs-parser" }
once_cell = "1.8"
dashmap = "5.4"
paste = "1.0"
errno = "0.2"
[profile.release]
debug = true
debug-assertions = false
lto = "fat"
opt-level = 3

[features]
gc-satb = ["rsgc/gc-satb"]
gc-incremental-update = ["rsgc/gc-incremental-update"]
gc-passive = ["rsgc/gc-passive"]
code-profiling = []


default = ["gc-incremental-update"]