[package]
name = "capy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
b3 = { git = "https://github.com/playxe/b3-rs" }
rsgc = { path = "rsgc" }
memoffset = { version = "0.8", features = ["unstable_const"] }
r7rs-parser = { git = "https://github.com/playxe/r7rs-parser" }
once_cell = "1.8"
dashmap = "5.4"
num = "0.4"
pretty = { version = "0.12", features = ["termcolor"] }
termcolor = "1.1"