[package]
name = "capy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsgc = { git = "https://github.com/playxe/rsgc" }
#b3 = "0.1"
macroassembler = "0.1"
r7rs-parser = { git = "https://github.com/playxe/r7rs-parser" }
once_cell = "1.8"
pretty = { version = "0.12", features = ["termcolor"] }
termcolor = "1.1.2"
env_logger = "0.10"
libc = "0.2"
url = "2.2.2"
parse-display = "0.8"
errno = "0.3"
cfg-if = "1.0"
naked-function = "0.1"
rustyline = { version = "12.0", features = [
    "custom-bindings",
] }
structopt = "0.3"

[profile.release]
lto = true
strip = true
opt-level = 2