[package]
name = "capy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsgc = { git = "https://github.com/playxe/rsgc" }
dashmap = "5.4"
once_cell = "1.8"
r7rs-parser = { git = "https://github.com/playxe/r7rs-parser" }
pretty = { version = "0.12", features = ["termcolor"] }
termcolor = "1.1.2"
env_logger = "0.10"
