[package]
name = "capy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsgc = { git = "https://github.com/playxe/rsgc" }
macroassembler = "0.1.1"
jit-allocator = "0.2.8"
once_cell = "1.8"
pretty = { version = "0.12", features = ["termcolor"] }
termcolor = "1.1.2"
env_logger = "0.10"
libloading = "0.8"
libc = "0.2"
tinyvec = { version = "1.6", features = ["alloc"] }
parse-display = "0.8"
paste = '1.0'
errno = "0.3"
num = "0.4"
murmur3 = "0.5"
cfg-if = "1.0"
naked-function = "0.1"
structopt = "0.3"
libffi = "3.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
    "memoryapi",
    "winnt",
    "sysinfoapi",
    "minwinbase",
    "errhandlingapi",
    "excpt",
    "minwindef",
    "profileapi",
    "processthreadsapi"
] }


[profile.release]
lto = true
strip = true
opt-level = 2

[features]
profile-opcodes = []