[package]
name = "capy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsgc = { git = "https://github.com/playxe/rsgc" }
dashmap = "5.4"
once_cell = "1.8"
